$axure.loadCurrentPage({
  "url":"状态三（已开通）.html",
  "generationDate":new Date(1508494785205.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54f3b95b4ac7470c908a267707e27d1e",
    "type":"Axure:Page",
    "name":"状态三（已开通）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1f3d9eb793ba40a592ac89d62ea774e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":360,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4362940bbc746d19044b7ca2a7bfbe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":130},
                "size":{
                  "width":360,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u0.png"}},
{
          "id":"e0b002fd43f1470e88dec4045660e574",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":78,
              "y":130},
            "size":{
              "width":157,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5fcf670c9054ba9b38d062490cde915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":78,
                  "y":130},
                "size":{
                  "width":157,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf42bc7749594007bd179cc9b3fdcb6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "lineSpacing":"18px",
            "location":{
              "x":244,
              "y":130},
            "size":{
              "width":157,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79a8b165ff6c41a4b7bfdc6adb30c958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "lineSpacing":"18px",
                "location":{
                  "x":244,
                  "y":130},
                "size":{
                  "width":157,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eac647f907a54b0d983d0e9579dd6d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":91},
            "size":{
              "width":580,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38e0a6d65a3e46af97302846b993c5ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":91},
                "size":{
                  "width":580,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f2393e14c1f44b692df510c4a1a93ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":78,
              "y":194},
            "size":{
              "width":157,
              "height":36},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0567af3f03f54057b694a22049fcc9fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":78,
                  "y":194},
                "size":{
                  "width":157,
                  "height":36},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u82.png"}},
{
          "id":"065fabe184ff4a0b83390c27f96edc31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":244,
              "y":194},
            "size":{
              "width":157,
              "height":36},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afcfcc8b5a944ec09ed54937da2f220a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":244,
                  "y":194},
                "size":{
                  "width":157,
                  "height":36},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u84.png"}},
{
          "id":"7cb71e5cfcf7439ca436c52e12467f33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":70,
              "y":187},
            "size":{
              "width":340,
              "height":53},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6893ca58504c6eafe97350e5835c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":70,
                  "y":187},
                "size":{
                  "width":340,
                  "height":53},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u14.png"}},
{
          "id":"dae51cdc38b5412494a25a69c55f60e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":320},
            "size":{
              "width":200,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27835b46f0674f4a8e73f8d35055b0cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":320},
                "size":{
                  "width":200,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u16.png"}},
{
          "id":"e5e60150d2c3441b8f93ccf1e3d7f73c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":240},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b602531176394cb4b58634964097ba65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":240},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"2ad6399ed7e244f7b8efedc59b3b550b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":162},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe119bac4a1a462b88708cc5b34c392c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":162},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"34aeb6c3079841f39bd26e701e739938",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":120},
            "size":{
              "width":200,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"469186cbbb064538a7a9556b0bebd129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":120},
                "size":{
                  "width":200,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态三（已开通）/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1f3d9eb793ba40a592ac89d62ea774e6":{
      "scriptId":"u0"},
    "a4362940bbc746d19044b7ca2a7bfbe3":{
      "scriptId":"u1"},
    "e0b002fd43f1470e88dec4045660e574":{
      "scriptId":"u2"},
    "e5fcf670c9054ba9b38d062490cde915":{
      "scriptId":"u3"},
    "cf42bc7749594007bd179cc9b3fdcb6b":{
      "scriptId":"u4"},
    "79a8b165ff6c41a4b7bfdc6adb30c958":{
      "scriptId":"u5"},
    "eac647f907a54b0d983d0e9579dd6d30":{
      "scriptId":"u6"},
    "38e0a6d65a3e46af97302846b993c5ca":{
      "scriptId":"u7"},
    "8f2393e14c1f44b692df510c4a1a93ef":{
      "scriptId":"u8"},
    "0567af3f03f54057b694a22049fcc9fc":{
      "scriptId":"u9"},
    "065fabe184ff4a0b83390c27f96edc31":{
      "scriptId":"u10"},
    "afcfcc8b5a944ec09ed54937da2f220a":{
      "scriptId":"u11"},
    "7cb71e5cfcf7439ca436c52e12467f33":{
      "scriptId":"u12"},
    "8b6893ca58504c6eafe97350e5835c0a":{
      "scriptId":"u13"},
    "dae51cdc38b5412494a25a69c55f60e8":{
      "scriptId":"u14"},
    "27835b46f0674f4a8e73f8d35055b0cc":{
      "scriptId":"u15"},
    "e5e60150d2c3441b8f93ccf1e3d7f73c":{
      "scriptId":"u16"},
    "b602531176394cb4b58634964097ba65":{
      "scriptId":"u17"},
    "2ad6399ed7e244f7b8efedc59b3b550b":{
      "scriptId":"u18"},
    "fe119bac4a1a462b88708cc5b34c392c":{
      "scriptId":"u19"},
    "34aeb6c3079841f39bd26e701e739938":{
      "scriptId":"u20"},
    "469186cbbb064538a7a9556b0bebd129":{
      "scriptId":"u21"}}});