$axure.loadCurrentPage({
  "url":"累计收益.html",
  "generationDate":new Date(1509069525726.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ac11014732a0402da9514be6b977ffec",
    "type":"Axure:Page",
    "name":"累计收益",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"215298c6271a44ff8fd0ce1f00935611",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":60},
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb28fdaeceb440009827540ab6af23ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u0.png"}},
{
          "id":"b820a767b4c9468884716cedd9ec2498",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08d37708845e495b8c5b23a3352ba807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u2.png"}},
{
          "id":"9440470732a548e392260a4faa12d152",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ffe66d71c444329d0c23f421570b77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"8a86d3254f784bf093d74972c6a9b6d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1139a2948f984795940166bc9b740323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"b9cbf82885f64c4ab1377a812ca02ebb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee5d788902f4a04a31197e0695e4e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"ea52abcc4072405da5839108f7a5e11d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":130},
            "size":{
              "width":317,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1595ae5e26054ce78b693bdbd8df8d80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":130},
                "size":{
                  "width":317,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u10.png"}},
{
          "id":"3722ba1b59b742adbe021399fc6eac4b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":299},
            "size":{
              "width":90,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/累计收益/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u12_line.png"}},
{
          "id":"dfe9c0d3afc4428a97ef8e6aba652fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":264},
            "size":{
              "width":220,
              "height":82},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b88d34c24f4c4cb1cc24af0a386c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":264},
                "size":{
                  "width":220,
                  "height":82},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u13.png"}},
{
          "id":"9a69eeddbd624f45a81a96ea3c5995a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":145},
            "size":{
              "width":126,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/累计收益/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u15_line.png"}},
{
          "id":"17f57b575c6a48f8ab07dd7bed4e8a48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":112},
            "size":{
              "width":220,
              "height":76},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b709643ab4434757ac6c6bf89936ffe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":112},
                "size":{
                  "width":220,
                  "height":76},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u16.png"}},
{
          "id":"af8a7a68bb8b42d7b8b4155d352bc6d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":790,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1bbaa5a86ed49038909be5f288af822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":790,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"9da221186c9e447d8c8a04d0da7048ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82580d9fc3dd4643aedecad115bb6a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"66fc48c48200469b858437acdcdb2553",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e89c50b4fe473794d9122f8bb41357",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"3978af384a48409cbff468f214e200b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":812,
              "y":130},
            "size":{
              "width":317,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42fe6ff3dd554ed98fa8fedd493cfba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":812,
                  "y":130},
                "size":{
                  "width":317,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u10.png"}},
{
          "id":"a4afa9a4e0634b848793ecf63d32c537",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":170},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u26_line.png"}},
{
          "id":"42a7c4ba94b447e89d3d6e1ffbe878f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":934,
              "y":270},
            "size":{
              "width":50,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57a19c21a1934efc9cbce9ad327ef25e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":934,
                  "y":270},
                "size":{
                  "width":50,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u27.png"}},
{
          "id":"ddaa9f357de14a39b7de8bf0303dbf7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":948,
              "y":284},
            "size":{
              "width":50,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243ffbd60a8749a997fa1ee1cf9378a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":948,
                  "y":284},
                "size":{
                  "width":50,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u29.png"}},
{
          "id":"460f399ac3844edf99d7b69ab832e69b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":958,
              "y":312},
            "size":{
              "width":33,
              "height":3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef74ce8c95e14c96a79538bb966587a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":958,
                  "y":312},
                "size":{
                  "width":33,
                  "height":3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u31.png"}},
{
          "id":"0f10e29171a743df94e501b8b5e742cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":958,
              "y":320},
            "size":{
              "width":25,
              "height":3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d59499b87c2404fbac4b59df2485ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":958,
                  "y":320},
                "size":{
                  "width":25,
                  "height":3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u33.png"}},
{
          "id":"a4e4fcecd193425594b7a9a44249a786",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":958,
              "y":330},
            "size":{
              "width":20,
              "height":3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dbbcddfbc79482dbc432619f0df4750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":958,
                  "y":330},
                "size":{
                  "width":20,
                  "height":3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u35.png"}},
{
          "id":"2b795a169e144833acfc65c8f42cd2b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":958,
              "y":298},
            "size":{
              "width":17,
              "height":9},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"299d2460059047eb97f8149d65a0ad7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":958,
                  "y":298},
                "size":{
                  "width":17,
                  "height":9},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u37.png"}},
{
          "id":"70053e2a75a14c12a8709d61cca76854",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":974,
              "y":316},
            "size":{
              "width":33,
              "height":33},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34febec315c4d1c89fb14b6886bc725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":974,
                  "y":316},
                "size":{
                  "width":33,
                  "height":33},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u39.png"}},
{
          "id":"450ff2038f904f5fbc6af0745c7e5cf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":981,
              "y":323},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15b1fe8439e44f099aea0e5df4e5bd05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":981,
                  "y":323},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u41.png"}},
{
          "id":"ce1b4dc041d74174b3e759eb25995121",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":996,
              "y":341},
            "size":{
              "width":9,
              "height":5},
            "rotation":"45",
            "textRotation":"45",
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a70b5302087d4f3e810c00cb827bdced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":996,
                  "y":341},
                "size":{
                  "width":9,
                  "height":5},
                "rotation":"45",
                "textRotation":"45",
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u43.png"}},
{
          "id":"430c9af09a114fb8a765a75ca7d35cda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":928,
              "y":374},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda23719d813408097ab58e35d4fa894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":928,
                  "y":374},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7b51189f233419892e2f2117cd766ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":188},
            "size":{
              "width":220,
              "height":76},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e058983895e457d9b56e77e74751aaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":188},
                "size":{
                  "width":220,
                  "height":76},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "215298c6271a44ff8fd0ce1f00935611":{
      "scriptId":"u0"},
    "fb28fdaeceb440009827540ab6af23ef":{
      "scriptId":"u1"},
    "b820a767b4c9468884716cedd9ec2498":{
      "scriptId":"u2"},
    "08d37708845e495b8c5b23a3352ba807":{
      "scriptId":"u3"},
    "9440470732a548e392260a4faa12d152":{
      "scriptId":"u4"},
    "e7ffe66d71c444329d0c23f421570b77":{
      "scriptId":"u5"},
    "8a86d3254f784bf093d74972c6a9b6d9":{
      "scriptId":"u6"},
    "1139a2948f984795940166bc9b740323":{
      "scriptId":"u7"},
    "b9cbf82885f64c4ab1377a812ca02ebb":{
      "scriptId":"u8"},
    "eee5d788902f4a04a31197e0695e4e01":{
      "scriptId":"u9"},
    "ea52abcc4072405da5839108f7a5e11d":{
      "scriptId":"u10"},
    "1595ae5e26054ce78b693bdbd8df8d80":{
      "scriptId":"u11"},
    "3722ba1b59b742adbe021399fc6eac4b":{
      "scriptId":"u12"},
    "dfe9c0d3afc4428a97ef8e6aba652fd1":{
      "scriptId":"u13"},
    "64b88d34c24f4c4cb1cc24af0a386c62":{
      "scriptId":"u14"},
    "9a69eeddbd624f45a81a96ea3c5995a2":{
      "scriptId":"u15"},
    "17f57b575c6a48f8ab07dd7bed4e8a48":{
      "scriptId":"u16"},
    "b709643ab4434757ac6c6bf89936ffe5":{
      "scriptId":"u17"},
    "af8a7a68bb8b42d7b8b4155d352bc6d8":{
      "scriptId":"u18"},
    "d1bbaa5a86ed49038909be5f288af822":{
      "scriptId":"u19"},
    "9da221186c9e447d8c8a04d0da7048ba":{
      "scriptId":"u20"},
    "82580d9fc3dd4643aedecad115bb6a99":{
      "scriptId":"u21"},
    "66fc48c48200469b858437acdcdb2553":{
      "scriptId":"u22"},
    "58e89c50b4fe473794d9122f8bb41357":{
      "scriptId":"u23"},
    "3978af384a48409cbff468f214e200b7":{
      "scriptId":"u24"},
    "42fe6ff3dd554ed98fa8fedd493cfba6":{
      "scriptId":"u25"},
    "a4afa9a4e0634b848793ecf63d32c537":{
      "scriptId":"u26"},
    "42a7c4ba94b447e89d3d6e1ffbe878f1":{
      "scriptId":"u27"},
    "57a19c21a1934efc9cbce9ad327ef25e":{
      "scriptId":"u28"},
    "ddaa9f357de14a39b7de8bf0303dbf7a":{
      "scriptId":"u29"},
    "243ffbd60a8749a997fa1ee1cf9378a4":{
      "scriptId":"u30"},
    "460f399ac3844edf99d7b69ab832e69b":{
      "scriptId":"u31"},
    "ef74ce8c95e14c96a79538bb966587a4":{
      "scriptId":"u32"},
    "0f10e29171a743df94e501b8b5e742cd":{
      "scriptId":"u33"},
    "8d59499b87c2404fbac4b59df2485ee0":{
      "scriptId":"u34"},
    "a4e4fcecd193425594b7a9a44249a786":{
      "scriptId":"u35"},
    "8dbbcddfbc79482dbc432619f0df4750":{
      "scriptId":"u36"},
    "2b795a169e144833acfc65c8f42cd2b6":{
      "scriptId":"u37"},
    "299d2460059047eb97f8149d65a0ad7b":{
      "scriptId":"u38"},
    "70053e2a75a14c12a8709d61cca76854":{
      "scriptId":"u39"},
    "a34febec315c4d1c89fb14b6886bc725":{
      "scriptId":"u40"},
    "450ff2038f904f5fbc6af0745c7e5cf2":{
      "scriptId":"u41"},
    "15b1fe8439e44f099aea0e5df4e5bd05":{
      "scriptId":"u42"},
    "ce1b4dc041d74174b3e759eb25995121":{
      "scriptId":"u43"},
    "a70b5302087d4f3e810c00cb827bdced":{
      "scriptId":"u44"},
    "430c9af09a114fb8a765a75ca7d35cda":{
      "scriptId":"u45"},
    "cda23719d813408097ab58e35d4fa894":{
      "scriptId":"u46"},
    "d7b51189f233419892e2f2117cd766ee":{
      "scriptId":"u47"},
    "8e058983895e457d9b56e77e74751aaa":{
      "scriptId":"u48"}}});