$axure.loadCurrentPage({
  "url":"明细详情.html",
  "generationDate":new Date(1509069526689.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4367e49682534cdb908c1efeb580d17b",
    "type":"Axure:Page",
    "name":"明细详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"602d6c120deb4f85afb8d282f1d6dba8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"986646bc59604b9d83dfb838d9f95a7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u0.png"}},
{
          "id":"5a51fb59987a41d197a2a0e94b15df40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc95ea6d85574af69688346d74503f3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"5d7d53f4ecc847759c997a60097d4cec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c6a4e1d44f74ef3be48a6751a5ffc40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"9a592489ecdd44eb9de712718afe2eeb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be309b57ea534527838f1d50ac6c4ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"69dae1cfbbff44f482101079faa3cf92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761bce8105494efd82bb1aad7f279ed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u8.png"}},
{
          "id":"1f402528c651471286e5bde80d95d7da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb90670e06cc448997e6cc0f042b091a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u10.png"}},
{
          "id":"7c740017e2f14595a5f5b1bf51b9972d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":520,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e25732b7d134ec0a8f03dd60693a49a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":520,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"dc1a34daba3845deb7778ac85e6fa81b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f16bca124aaf43668a17edc098240db9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"44d4ec996cf844a0be85defba7acb6f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ace55d71a2d4263a2a4ffd529c7d151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"5a425958ddf545ba961aa63b15640d71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":980,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7d8814603f41ababc44beee4ae88da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":980,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"e0abce3bbc724845824e195ce2999eb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf974b8b448433b9ca260af1e9fe8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"52bd3ab0a5da4b03933e2143044f6cd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034e53e05bf64e49ae1982fe2b8d6ab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"ef7e65eb5d064ac5bc84041c342a88da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":61,
              "y":146},
            "size":{
              "width":358,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a69ff686e6d4c06ae37f0e194eacf95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":61,
                  "y":146},
                "size":{
                  "width":358,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u24.png"}},
{
          "id":"024e8e6417b74e29afd9e4ea425e9533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":200,
              "y":398},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca679a3d49dd40a59de3acaf7b2ccf56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":200,
                  "y":398},
                "size":{
                  "width":200,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u26.png"}},
{
          "id":"178e0d2bc5d84fe79cf40b9814134a7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":521,
              "y":146},
            "size":{
              "width":358,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d23eeb05906d42a2ace4d6eeb6c0adc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":521,
                  "y":146},
                "size":{
                  "width":358,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u24.png"}},
{
          "id":"27f7643e368242e8adba3ee07f1b0d80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":981,
              "y":146},
            "size":{
              "width":358,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d766c54600b4d60bbe63f0f125fe803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":981,
                  "y":146},
                "size":{
                  "width":358,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u24.png"}},
{
          "id":"255028ef888c4f02a5086f29eaba4f71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1120,
              "y":296},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69589cf275e497787796109902f87a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1120,
                  "y":296},
                "size":{
                  "width":200,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u26.png"}},
{
          "id":"a18be6fad5654d87b8cd947711c71e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":521,
              "y":246},
            "size":{
              "width":358,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6b5e7070123481ea89147ec1a052089",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":521,
                  "y":246},
                "size":{
                  "width":358,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u34.png"}},
{
          "id":"db5c4fc0bd6a4f55a23477503ebd3290",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23B798,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":981,
              "y":246},
            "size":{
              "width":358,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ef31b575ac438cb3e08bc6600cf3a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23B798,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":981,
                  "y":246},
                "size":{
                  "width":358,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u34.png"}},
{
          "id":"b3cf2766161244a291e8b9e7c7ef81b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":290},
            "size":{
              "width":360,
              "height":100},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64897e9f6ce1405ba6f5333841d66fbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":290},
                "size":{
                  "width":360,
                  "height":100},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u38.png"}},
{
          "id":"25300e7cb39f4d3a939a04e4acd930d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1430,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c6c3063ab484ed1a3e7020336999889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1430,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u10.png"}},
{
          "id":"eeb5374d10e34a218208ace32e86be8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":1430,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e616909d83d45948463809eaa8c078f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":1430,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"e291cb4cb4e3465994f14814d25da1d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1430,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a178007e19e14bc885b559a58ca6f0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1430,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"b37e72852fee458ba6974c88f57f2e38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1430,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0da5c942242b486cbe1bdcd073114b1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1430,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"44adb3f8b0e641758914bbca3837a18c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1431,
              "y":146},
            "size":{
              "width":358,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c89a17b1d334898a7e1898f84bffb79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1431,
                  "y":146},
                "size":{
                  "width":358,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u24.png"}},
{
          "id":"9f4da888c41d446195a5be1f9a6c4f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1722,
              "y":305},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da8eafc26454b0a90d9cd625b4cc5bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1722,
                  "y":305},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u50.png"}},
{
          "id":"2a0445600f05444995df0b030f167e18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1450,
              "y":334},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1136b3095c164e22ae244a9eb4e79db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1450,
                  "y":334},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u52.png"}},
{
          "id":"e0c0e7c7189943178c68aff159a78ddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1619,
              "y":334},
            "size":{
              "width":151,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c403a900cb4490096610a66cc7309d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1619,
                  "y":334},
                "size":{
                  "width":151,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u54.png"}},
{
          "id":"9a0e49ae5369457c9190623ffa188aad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":392},
            "size":{
              "width":360,
              "height":304},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb2fb6cc80a4606a399676a8e32a5cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":392},
                "size":{
                  "width":360,
                  "height":304},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u56.png"}},
{
          "id":"ff8b979e0f3341e8888d162fb061008d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":740.5},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4db1cd348ff4ce19b44a5f83f18a594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":740.5},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/明细详情/u58.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "602d6c120deb4f85afb8d282f1d6dba8":{
      "scriptId":"u0"},
    "986646bc59604b9d83dfb838d9f95a7b":{
      "scriptId":"u1"},
    "5a51fb59987a41d197a2a0e94b15df40":{
      "scriptId":"u2"},
    "bc95ea6d85574af69688346d74503f3f":{
      "scriptId":"u3"},
    "5d7d53f4ecc847759c997a60097d4cec":{
      "scriptId":"u4"},
    "8c6a4e1d44f74ef3be48a6751a5ffc40":{
      "scriptId":"u5"},
    "9a592489ecdd44eb9de712718afe2eeb":{
      "scriptId":"u6"},
    "be309b57ea534527838f1d50ac6c4ddc":{
      "scriptId":"u7"},
    "69dae1cfbbff44f482101079faa3cf92":{
      "scriptId":"u8"},
    "761bce8105494efd82bb1aad7f279ed1":{
      "scriptId":"u9"},
    "1f402528c651471286e5bde80d95d7da":{
      "scriptId":"u10"},
    "bb90670e06cc448997e6cc0f042b091a":{
      "scriptId":"u11"},
    "7c740017e2f14595a5f5b1bf51b9972d":{
      "scriptId":"u12"},
    "4e25732b7d134ec0a8f03dd60693a49a":{
      "scriptId":"u13"},
    "dc1a34daba3845deb7778ac85e6fa81b":{
      "scriptId":"u14"},
    "f16bca124aaf43668a17edc098240db9":{
      "scriptId":"u15"},
    "44d4ec996cf844a0be85defba7acb6f0":{
      "scriptId":"u16"},
    "4ace55d71a2d4263a2a4ffd529c7d151":{
      "scriptId":"u17"},
    "5a425958ddf545ba961aa63b15640d71":{
      "scriptId":"u18"},
    "ea7d8814603f41ababc44beee4ae88da":{
      "scriptId":"u19"},
    "e0abce3bbc724845824e195ce2999eb3":{
      "scriptId":"u20"},
    "bdf974b8b448433b9ca260af1e9fe8db":{
      "scriptId":"u21"},
    "52bd3ab0a5da4b03933e2143044f6cd5":{
      "scriptId":"u22"},
    "034e53e05bf64e49ae1982fe2b8d6ab7":{
      "scriptId":"u23"},
    "ef7e65eb5d064ac5bc84041c342a88da":{
      "scriptId":"u24"},
    "2a69ff686e6d4c06ae37f0e194eacf95":{
      "scriptId":"u25"},
    "024e8e6417b74e29afd9e4ea425e9533":{
      "scriptId":"u26"},
    "ca679a3d49dd40a59de3acaf7b2ccf56":{
      "scriptId":"u27"},
    "178e0d2bc5d84fe79cf40b9814134a7a":{
      "scriptId":"u28"},
    "d23eeb05906d42a2ace4d6eeb6c0adc0":{
      "scriptId":"u29"},
    "27f7643e368242e8adba3ee07f1b0d80":{
      "scriptId":"u30"},
    "6d766c54600b4d60bbe63f0f125fe803":{
      "scriptId":"u31"},
    "255028ef888c4f02a5086f29eaba4f71":{
      "scriptId":"u32"},
    "c69589cf275e497787796109902f87a5":{
      "scriptId":"u33"},
    "a18be6fad5654d87b8cd947711c71e23":{
      "scriptId":"u34"},
    "f6b5e7070123481ea89147ec1a052089":{
      "scriptId":"u35"},
    "db5c4fc0bd6a4f55a23477503ebd3290":{
      "scriptId":"u36"},
    "33ef31b575ac438cb3e08bc6600cf3a8":{
      "scriptId":"u37"},
    "b3cf2766161244a291e8b9e7c7ef81b1":{
      "scriptId":"u38"},
    "64897e9f6ce1405ba6f5333841d66fbf":{
      "scriptId":"u39"},
    "25300e7cb39f4d3a939a04e4acd930d8":{
      "scriptId":"u40"},
    "6c6c3063ab484ed1a3e7020336999889":{
      "scriptId":"u41"},
    "eeb5374d10e34a218208ace32e86be8b":{
      "scriptId":"u42"},
    "0e616909d83d45948463809eaa8c078f":{
      "scriptId":"u43"},
    "e291cb4cb4e3465994f14814d25da1d5":{
      "scriptId":"u44"},
    "a178007e19e14bc885b559a58ca6f0b7":{
      "scriptId":"u45"},
    "b37e72852fee458ba6974c88f57f2e38":{
      "scriptId":"u46"},
    "0da5c942242b486cbe1bdcd073114b1d":{
      "scriptId":"u47"},
    "44adb3f8b0e641758914bbca3837a18c":{
      "scriptId":"u48"},
    "5c89a17b1d334898a7e1898f84bffb79":{
      "scriptId":"u49"},
    "9f4da888c41d446195a5be1f9a6c4f30":{
      "scriptId":"u50"},
    "8da8eafc26454b0a90d9cd625b4cc5bc":{
      "scriptId":"u51"},
    "2a0445600f05444995df0b030f167e18":{
      "scriptId":"u52"},
    "1136b3095c164e22ae244a9eb4e79db8":{
      "scriptId":"u53"},
    "e0c0e7c7189943178c68aff159a78ddd":{
      "scriptId":"u54"},
    "7c403a900cb4490096610a66cc7309d6":{
      "scriptId":"u55"},
    "9a0e49ae5369457c9190623ffa188aad":{
      "scriptId":"u56"},
    "dfb2fb6cc80a4606a399676a8e32a5cb":{
      "scriptId":"u57"},
    "ff8b979e0f3341e8888d162fb061008d":{
      "scriptId":"u58"},
    "d4db1cd348ff4ce19b44a5f83f18a594":{
      "scriptId":"u59"}}});