$axure.loadCurrentPage({
  "url":"七日年化.html",
  "generationDate":new Date(1508494787138.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e560125ff84a47359cf31ac8ed99689b",
    "type":"Axure:Page",
    "name":"七日年化",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88359a52ffef4807a341c668da74066b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f908be956c411bb500e977b6d8bad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u0.png"}},
{
          "id":"9235e208001f445f85627f2c3a0b3633",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c579360d7fee42ccba6c63dd22b0d059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"c9f65c1bce264429b8d86301788a3dc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6c03e98118f49a686cad972346e71a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u107.png"}},
{
          "id":"0d2fba4c20fd4e1997f7d9f59c3810f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adbce39a9f094dd9ba3490cd129f59ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"c88abc9e2e4a400799996cccc42bc75a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":299},
            "size":{
              "width":90,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/累计收益/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u12_line.png"}},
{
          "id":"92bbbd4e142b485298912cbfac566620",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":263},
            "size":{
              "width":220,
              "height":82},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0a164ed6134c7ebc58fdf623f36178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":263},
                "size":{
                  "width":220,
                  "height":82},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u13.png"}},
{
          "id":"92d6805f0b1d4cabbe8622aa11fc2a7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":130},
            "size":{
              "width":317,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b004e37a8614e1d820177b4f2eb3b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":130},
                "size":{
                  "width":317,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u10.png"}},
{
          "id":"8cd993fb90234f97bf9ecd2e5376d30a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":145},
            "size":{
              "width":126,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/累计收益/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u15_line.png"}},
{
          "id":"fac5aecc39e0422a866eb4c4e0fc2b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":112},
            "size":{
              "width":220,
              "height":76},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f72e93afe9f41eb80a2d3d66659a041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":112},
                "size":{
                  "width":220,
                  "height":76},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u16.png"}},
{
          "id":"58476eb42f80453a96b76728f6dd2b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE81D33,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":207},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91a9be3065174dd08620b9fd6a9286eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":207},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"3c896c03d770482689b37905cfb8dd61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":263},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5fb25f4cf6c483fbc5c91264e1809e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":263},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"c0ebb1272b4d48d6bbaa2f26382ff1e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":319},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd8d70bd38714ca5bc0877302e7e4001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":319},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"b64cdbd1929843f287c9bdd005bc1042",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":375},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b87f6fd81f2485f82a5ced832b271f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":375},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"bdf3ba0df69a4a959ec874cdf8460f90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":431},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd8a9cb3dff4be69ed9ebd4b7eeb032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":431},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"2a2d97869e594a00af139774614bdff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":487},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"199d3e058f5343e4ac77d0ab8e5f75dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":487},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"8d463b81e38c4b4eb46d41afdfc03cd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":543},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb80604beea342eeb278ed268236d2b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":543},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"f215952562c843fbb604f79d6157622f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":599},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"453f4224c5f84d998fc20d5616b0644f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":599},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}},
{
          "id":"272d4a2445554ae997bd4a61999b64fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":194,
              "y":655},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc26d0b6f5f40beb30ca8e26dc982fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":194,
                  "y":655},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/七日年化/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "88359a52ffef4807a341c668da74066b":{
      "scriptId":"u0"},
    "50f908be956c411bb500e977b6d8bad0":{
      "scriptId":"u1"},
    "9235e208001f445f85627f2c3a0b3633":{
      "scriptId":"u2"},
    "c579360d7fee42ccba6c63dd22b0d059":{
      "scriptId":"u3"},
    "c9f65c1bce264429b8d86301788a3dc8":{
      "scriptId":"u4"},
    "c6c03e98118f49a686cad972346e71a0":{
      "scriptId":"u5"},
    "0d2fba4c20fd4e1997f7d9f59c3810f9":{
      "scriptId":"u6"},
    "adbce39a9f094dd9ba3490cd129f59ec":{
      "scriptId":"u7"},
    "c88abc9e2e4a400799996cccc42bc75a":{
      "scriptId":"u8"},
    "92bbbd4e142b485298912cbfac566620":{
      "scriptId":"u9"},
    "cc0a164ed6134c7ebc58fdf623f36178":{
      "scriptId":"u10"},
    "92d6805f0b1d4cabbe8622aa11fc2a7b":{
      "scriptId":"u11"},
    "1b004e37a8614e1d820177b4f2eb3b6f":{
      "scriptId":"u12"},
    "8cd993fb90234f97bf9ecd2e5376d30a":{
      "scriptId":"u13"},
    "fac5aecc39e0422a866eb4c4e0fc2b40":{
      "scriptId":"u14"},
    "5f72e93afe9f41eb80a2d3d66659a041":{
      "scriptId":"u15"},
    "58476eb42f80453a96b76728f6dd2b2d":{
      "scriptId":"u16"},
    "91a9be3065174dd08620b9fd6a9286eb":{
      "scriptId":"u17"},
    "3c896c03d770482689b37905cfb8dd61":{
      "scriptId":"u18"},
    "b5fb25f4cf6c483fbc5c91264e1809e2":{
      "scriptId":"u19"},
    "c0ebb1272b4d48d6bbaa2f26382ff1e2":{
      "scriptId":"u20"},
    "bd8d70bd38714ca5bc0877302e7e4001":{
      "scriptId":"u21"},
    "b64cdbd1929843f287c9bdd005bc1042":{
      "scriptId":"u22"},
    "6b87f6fd81f2485f82a5ced832b271f5":{
      "scriptId":"u23"},
    "bdf3ba0df69a4a959ec874cdf8460f90":{
      "scriptId":"u24"},
    "bbd8a9cb3dff4be69ed9ebd4b7eeb032":{
      "scriptId":"u25"},
    "2a2d97869e594a00af139774614bdff6":{
      "scriptId":"u26"},
    "199d3e058f5343e4ac77d0ab8e5f75dd":{
      "scriptId":"u27"},
    "8d463b81e38c4b4eb46d41afdfc03cd1":{
      "scriptId":"u28"},
    "eb80604beea342eeb278ed268236d2b5":{
      "scriptId":"u29"},
    "f215952562c843fbb604f79d6157622f":{
      "scriptId":"u30"},
    "453f4224c5f84d998fc20d5616b0644f":{
      "scriptId":"u31"},
    "272d4a2445554ae997bd4a61999b64fb":{
      "scriptId":"u32"},
    "0fc26d0b6f5f40beb30ca8e26dc982fc":{
      "scriptId":"u33"}}});