$axure.loadCurrentPage({
  "url":"购买固收（需判断有_无xx宝本地账户）.html",
  "generationDate":new Date(1509069532972.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"42677363c552403ca19ed7f8ee597219",
    "type":"Axure:Page",
    "name":"购买固收（需判断有/无XX宝本地账户）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c0d582b3da824cac807223fdf177ba7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":126},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca861c7539d4a3987ae45458b95fb3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":126},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u0.png"}},
{
          "id":"ed675c7c3e024f9c8301ef4ddd131b63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":126},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef40cc963aa54cfebb2b00c3df9326d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":533,
                  "y":126},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u2.png"}},
{
          "id":"edce6a418c1e40c495005450e00a4da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "location":{
              "x":79,
              "y":444},
            "size":{
              "width":188,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18479edbf65c4dcda47354dce701f91f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "location":{
                  "x":79,
                  "y":444},
                "size":{
                  "width":188,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u4.png"}},
{
          "id":"9a473fb9daa3424e9c31040b18da0654",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":386},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"858f634c1a5a42a6b6aa1bb090c5e3f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":353,
                  "y":386},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"5ba28832a9184570af22c3a7e6ce8b28",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":464},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03787bd7f0ef4debbfa489309594db84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":876,
                  "y":464},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"6e53005ecaac4697bbe908e2f5094888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":183,
              "y":206},
            "size":{
              "width":114,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50096cbfd42844939abf6e43e5b49eb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":183,
                  "y":206},
                "size":{
                  "width":114,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u10.png"}},
{
          "id":"1670d4a54cad488590056fbd22613010",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "location":{
              "x":552,
              "y":476},
            "size":{
              "width":92,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8421d416c6d44744b529a0cf0bd487a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "location":{
                  "x":552,
                  "y":476},
                "size":{
                  "width":92,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u12.png"}},
{
          "id":"928f9c0dbd01419d85b6c6ae138df54e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":656,
              "y":206},
            "size":{
              "width":114,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b33132b1f841e4b700b244e7f61c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":656,
                  "y":206},
                "size":{
                  "width":114,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u10.png"}},
{
          "id":"925f051608a342b4a513f09c62a24e77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":838},
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c2f4788776460994ddfb8dd135276e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":838},
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u16.png"}},
{
          "id":"9a6738df6188468a8541052fda9a0b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xBF7B7B7D},
            "location":{
              "x":533,
              "y":838},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7B7B7D}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c3880386f84feb9e94e499e62d0f2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xBF7B7B7D},
                "location":{
                  "x":533,
                  "y":838},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7B7B7D}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u18.png"}},
{
          "id":"1f52a523188e4d24b58576af09cd497a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":1080},
            "size":{
              "width":280,
              "height":156},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4195c9a5c6f7488f864b72d31c16ae35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573,
                  "y":1080},
                "size":{
                  "width":280,
                  "height":156},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u20.png"}},
{
          "id":"84e0aad9434b473da43e6e1a2294cbc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":593,
              "y":1128},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a454c4ff984d60ab77139c26d9372e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":593,
                  "y":1128},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0a5666eb67e471c8c8c4fee41ac249c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":1189},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购买固收（需判断有_无xx宝本地账户）/u24_line.png"}},
{
          "id":"b5e2fe167781441c870037ce5d400d36",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":1194},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购买固收（需判断有_无xx宝本地账户）/u25_line.png"}},
{
          "id":"5334868146bf45b29fddc15d09eaafba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":573,
              "y":1194},
            "size":{
              "width":140,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efa71af20ba34e3ba88fedb4566bc0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":573,
                  "y":1194},
                "size":{
                  "width":140,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5719562a26d46ed8cc393b233058740",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":713,
              "y":1194},
            "size":{
              "width":140,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c394a6782c4c72bcea8c27fb678801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":713,
                  "y":1194},
                "size":{
                  "width":140,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5616cdb27bb48f98095c18c38a2560a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":593,
              "y":1095},
            "size":{
              "width":240,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c04d15dc7d1442ca8b7755fd1b215fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":593,
                  "y":1095},
                "size":{
                  "width":240,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23fb513870e49f29bc764212cdd2275",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE71D32,
              "opacity":1},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":59,
              "y":48},
            "size":{
              "width":519,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72ee64a73b464086925b24121b600498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32,
                  "opacity":1},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":59,
                  "y":48},
                "size":{
                  "width":519,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u32.png"}},
{
          "id":"ea9e187268d94d20a05b9eb716b61f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":573,
              "y":1036},
            "size":{
              "width":145,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d6fd5e3fc1747cf9ccbf2904ec280fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":573,
                  "y":1036},
                "size":{
                  "width":145,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u34.png"}},
{
          "id":"260e80add3ac492da43c9a42e8d51cd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE71D32,
              "opacity":1},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":1003,
              "y":429.5},
            "size":{
              "width":173,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d744958dabe4459ba74645797723d0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32,
                  "opacity":1},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":1003,
                  "y":429.5},
                "size":{
                  "width":173,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u36.png"}},
{
          "id":"201f1f0ae37446b28e13fafcae0a657a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "location":{
              "x":798,
              "y":430},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f21ff2f1e9ea4ebdac7a7efedaf44388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "location":{
                  "x":798,
                  "y":430},
                "size":{
                  "width":76,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u38.png"}},
{
          "id":"b74c9d4da0cf4ee2b31b39723fb5bbb0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670.200012207031,
              "y":462},
            "size":{
              "width":10,
              "height":52},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/购买固收（需判断有_无xx宝本地账户）/u40_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购买固收（需判断有_无xx宝本地账户）/u40_line.png"}},
{
          "id":"98dedd44fb7144c18296f2c2596cb7b2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":454},
            "size":{
              "width":10,
              "height":31},
            "rotation":"30",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/购买固收（需判断有_无xx宝本地账户）/u40_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购买固收（需判断有_无xx宝本地账户）/u41_line.png"}},
{
          "id":"1d226699d8e34024950ef2a45457d9d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE71D32,
              "opacity":1},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":687,
              "y":476},
            "size":{
              "width":133,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f67cd5b5d146d69b90adf7f5c7f3dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32,
                  "opacity":1},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":687,
                  "y":476},
                "size":{
                  "width":133,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u42.png"}},
{
          "id":"126c5cb3f8b341638b90cad730adb987",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "location":{
              "x":283,
              "y":1231},
            "size":{
              "width":55,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e6434a17e52456db6ba6c7bd50365a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "location":{
                  "x":283,
                  "y":1231},
                "size":{
                  "width":55,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u44.png"}},
{
          "id":"d3acc0b17c524d23a150f4f07da5a8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "location":{
              "x":249,
              "y":1115},
            "size":{
              "width":37,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a17fa12754f4e5997ef101d2cbe9e3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "location":{
                  "x":249,
                  "y":1115},
                "size":{
                  "width":37,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u46.png"}},
{
          "id":"7b6decd762cd4ef4bb844f28eb6d8e01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "location":{
              "x":249,
              "y":1164},
            "size":{
              "width":37,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75b26bc3c6342dab3a86bd08052faa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "location":{
                  "x":249,
                  "y":1164},
                "size":{
                  "width":37,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u46.png"}},
{
          "id":"f611bddff5e740e39543d659bb36f786",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":101,
              "y":1036},
            "size":{
              "width":133,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE71D32},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08c009dfa6244a70b44b3c2edb85d8aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":101,
                  "y":1036},
                "size":{
                  "width":133,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE71D32},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买固收（需判断有_无xx宝本地账户）/u50.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c0d582b3da824cac807223fdf177ba7b":{
      "scriptId":"u0"},
    "0ca861c7539d4a3987ae45458b95fb3a":{
      "scriptId":"u1"},
    "ed675c7c3e024f9c8301ef4ddd131b63":{
      "scriptId":"u2"},
    "ef40cc963aa54cfebb2b00c3df9326d2":{
      "scriptId":"u3"},
    "edce6a418c1e40c495005450e00a4da1":{
      "scriptId":"u4"},
    "18479edbf65c4dcda47354dce701f91f":{
      "scriptId":"u5"},
    "9a473fb9daa3424e9c31040b18da0654":{
      "scriptId":"u6"},
    "858f634c1a5a42a6b6aa1bb090c5e3f6":{
      "scriptId":"u7"},
    "5ba28832a9184570af22c3a7e6ce8b28":{
      "scriptId":"u8"},
    "03787bd7f0ef4debbfa489309594db84":{
      "scriptId":"u9"},
    "6e53005ecaac4697bbe908e2f5094888":{
      "scriptId":"u10"},
    "50096cbfd42844939abf6e43e5b49eb6":{
      "scriptId":"u11"},
    "1670d4a54cad488590056fbd22613010":{
      "scriptId":"u12"},
    "8421d416c6d44744b529a0cf0bd487a9":{
      "scriptId":"u13"},
    "928f9c0dbd01419d85b6c6ae138df54e":{
      "scriptId":"u14"},
    "89b33132b1f841e4b700b244e7f61c9b":{
      "scriptId":"u15"},
    "925f051608a342b4a513f09c62a24e77":{
      "scriptId":"u16"},
    "a7c2f4788776460994ddfb8dd135276e":{
      "scriptId":"u17"},
    "9a6738df6188468a8541052fda9a0b1a":{
      "scriptId":"u18"},
    "04c3880386f84feb9e94e499e62d0f2d":{
      "scriptId":"u19"},
    "1f52a523188e4d24b58576af09cd497a":{
      "scriptId":"u20"},
    "4195c9a5c6f7488f864b72d31c16ae35":{
      "scriptId":"u21"},
    "84e0aad9434b473da43e6e1a2294cbc6":{
      "scriptId":"u22"},
    "b7a454c4ff984d60ab77139c26d9372e":{
      "scriptId":"u23"},
    "e0a5666eb67e471c8c8c4fee41ac249c":{
      "scriptId":"u24"},
    "b5e2fe167781441c870037ce5d400d36":{
      "scriptId":"u25"},
    "5334868146bf45b29fddc15d09eaafba":{
      "scriptId":"u26"},
    "efa71af20ba34e3ba88fedb4566bc0ad":{
      "scriptId":"u27"},
    "b5719562a26d46ed8cc393b233058740":{
      "scriptId":"u28"},
    "d3c394a6782c4c72bcea8c27fb678801":{
      "scriptId":"u29"},
    "e5616cdb27bb48f98095c18c38a2560a":{
      "scriptId":"u30"},
    "2c04d15dc7d1442ca8b7755fd1b215fd":{
      "scriptId":"u31"},
    "d23fb513870e49f29bc764212cdd2275":{
      "scriptId":"u32"},
    "72ee64a73b464086925b24121b600498":{
      "scriptId":"u33"},
    "ea9e187268d94d20a05b9eb716b61f34":{
      "scriptId":"u34"},
    "4d6fd5e3fc1747cf9ccbf2904ec280fa":{
      "scriptId":"u35"},
    "260e80add3ac492da43c9a42e8d51cd0":{
      "scriptId":"u36"},
    "8d744958dabe4459ba74645797723d0e":{
      "scriptId":"u37"},
    "201f1f0ae37446b28e13fafcae0a657a":{
      "scriptId":"u38"},
    "f21ff2f1e9ea4ebdac7a7efedaf44388":{
      "scriptId":"u39"},
    "b74c9d4da0cf4ee2b31b39723fb5bbb0":{
      "scriptId":"u40"},
    "98dedd44fb7144c18296f2c2596cb7b2":{
      "scriptId":"u41"},
    "1d226699d8e34024950ef2a45457d9d4":{
      "scriptId":"u42"},
    "99f67cd5b5d146d69b90adf7f5c7f3dc":{
      "scriptId":"u43"},
    "126c5cb3f8b341638b90cad730adb987":{
      "scriptId":"u44"},
    "0e6434a17e52456db6ba6c7bd50365a4":{
      "scriptId":"u45"},
    "d3acc0b17c524d23a150f4f07da5a8aa":{
      "scriptId":"u46"},
    "3a17fa12754f4e5997ef101d2cbe9e3f":{
      "scriptId":"u47"},
    "7b6decd762cd4ef4bb844f28eb6d8e01":{
      "scriptId":"u48"},
    "a75b26bc3c6342dab3a86bd08052faa1":{
      "scriptId":"u49"},
    "f611bddff5e740e39543d659bb36f786":{
      "scriptId":"u50"},
    "08c009dfa6244a70b44b3c2edb85d8aa":{
      "scriptId":"u51"}}});