$axure.loadCurrentPage({
  "url":"提现（无xx宝本地账户）.html",
  "generationDate":new Date(1509069532311.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d2f99a196e6348f29abe1985802091a9",
    "type":"Axure:Page",
    "name":"提现（无XX宝本地账户）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d88cb2d82ac94e9eb2aa968059d2480b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":501.538452148438,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59afa827b86143779b37e1abcaaa4202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501.538452148438,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u0.png"}},
{
          "id":"073963594fc2410b9ecff9f7275dea60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85bf55b25e9450f82a3ea34975d6309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u2.png"}},
{
          "id":"03d68603a95947bd8157c69a46ff0805",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":948,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a978674c7feb4bb98d21657d3137ddbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":948,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u4.png"}},
{
          "id":"12c7d07c828d49d985ea62f8749db670",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1388.75,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"627045f028934f40970b04ab59d3102c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1388.75,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u6.png"}},
{
          "id":"a792bca00ab34150a4074adf70aeed70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1860,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38e99dfddfda43d3be5b0c491eda2590",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1860,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u8.png"}},
{
          "id":"29ba504d93574fb4b090eae37f14c3c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2303,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d243357b561044c29a3c433c1d598bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2303,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u10.png"}},
{
          "id":"eb16120f604f4f5c8906f519d424b873",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":622,
              "y":396},
            "size":{
              "width":130,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9785fd37df747a29d3b0b7acddc523b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":622,
                  "y":396},
                "size":{
                  "width":130,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u12.png"}},
{
          "id":"7a3c61fdc8ec44e0a5fd0c2449060e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":175,
              "y":116},
            "size":{
              "width":130,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccfcc97157ec491a9dd40238b74e8694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":175,
                  "y":116},
                "size":{
                  "width":130,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u12.png"}},
{
          "id":"69c2558bb27d40b1a6567f9e1cad5691",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":141,
              "y":337},
            "size":{
              "width":69,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7579926453945ae8b0b214e40ddfccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":141,
                  "y":337},
                "size":{
                  "width":69,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u16.png"}},
{
          "id":"06dc85d289a74b4d95569c97c490e018",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":983,
              "y":317},
            "size":{
              "width":165,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fe32dd66abf4a69bd90d173b82f5567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":983,
                  "y":317},
                "size":{
                  "width":165,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u18.png"}},
{
          "id":"9839d4bc8666406e8c8ea6cc19a4674f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":2400,
              "y":351},
            "size":{
              "width":165,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95ff22b10974afab3e64855aaaeb25d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":2400,
                  "y":351},
                "size":{
                  "width":165,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u18.png"}},
{
          "id":"7215821aaa1e4a3985fff4effce225ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":206,
              "y":565},
            "size":{
              "width":69,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9aaea76ac8641e2b5d51558f4cdf5d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":206,
                  "y":565},
                "size":{
                  "width":69,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u16.png"}},
{
          "id":"1506fe13790046a5b61f137d2aedc263",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":1408,
              "y":231},
            "size":{
              "width":89,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7a2f93a2864cec846f111b754a6e64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":1408,
                  "y":231},
                "size":{
                  "width":89,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u24.png"}},
{
          "id":"b1d07d7c324d4a1e8c4587b92e67c20b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":1408,
              "y":333},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da286518ec14d2badaadc12a64f1c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":1408,
                  "y":333},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u26.png"}},
{
          "id":"c16db1c0996c46fb938fdd1f3dd902d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1487,
              "y":408},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946d0cf8042749a38d0b123d2161c0a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1487,
                  "y":408},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"2bbc05947e854b96be738af16d61195b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1600,
              "y":408},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05c666bda2af4bceb9fd1f7f03d0c3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1600,
                  "y":408},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"4f330ee20785460097c53092af003425",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1490,
              "y":430},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d5275ae6f14272bc0e72d4c66d8bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1490,
                  "y":430},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"563d8689439b4073804cb763d937ea50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1603,
              "y":430},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dfe94ef1d96454189579724e83a3cb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1603,
                  "y":430},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"5574dc41419a4a9fb20bc8d88c38d28f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1532.5,
              "y":551.5},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"250eb5ad06614dbbbda53ebfcabf3207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1532.5,
                  "y":551.5},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"695d3859d9264296a27af857c4c04dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1515.5,
              "y":578.5},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba23ddbc6730491a8f6fce83f1ec822c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1515.5,
                  "y":578.5},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"a76f49a60836490ab62c64bf50eb81d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1528.5,
              "y":622},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c04f6a3f62bd4064a8cded6aa7dabc5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1528.5,
                  "y":622},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}},
{
          "id":"3a666b89048f400db4a2f655674b3560",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1516,
              "y":648},
            "size":{
              "width":35,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b8c6a48e0c40e3aa74f3fa4cc307b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1516,
                  "y":648},
                "size":{
                  "width":35,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现（无xx宝本地账户）/u28.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d88cb2d82ac94e9eb2aa968059d2480b":{
      "scriptId":"u0"},
    "59afa827b86143779b37e1abcaaa4202":{
      "scriptId":"u1"},
    "073963594fc2410b9ecff9f7275dea60":{
      "scriptId":"u2"},
    "f85bf55b25e9450f82a3ea34975d6309":{
      "scriptId":"u3"},
    "03d68603a95947bd8157c69a46ff0805":{
      "scriptId":"u4"},
    "a978674c7feb4bb98d21657d3137ddbd":{
      "scriptId":"u5"},
    "12c7d07c828d49d985ea62f8749db670":{
      "scriptId":"u6"},
    "627045f028934f40970b04ab59d3102c":{
      "scriptId":"u7"},
    "a792bca00ab34150a4074adf70aeed70":{
      "scriptId":"u8"},
    "38e99dfddfda43d3be5b0c491eda2590":{
      "scriptId":"u9"},
    "29ba504d93574fb4b090eae37f14c3c8":{
      "scriptId":"u10"},
    "d243357b561044c29a3c433c1d598bd2":{
      "scriptId":"u11"},
    "eb16120f604f4f5c8906f519d424b873":{
      "scriptId":"u12"},
    "f9785fd37df747a29d3b0b7acddc523b":{
      "scriptId":"u13"},
    "7a3c61fdc8ec44e0a5fd0c2449060e0a":{
      "scriptId":"u14"},
    "ccfcc97157ec491a9dd40238b74e8694":{
      "scriptId":"u15"},
    "69c2558bb27d40b1a6567f9e1cad5691":{
      "scriptId":"u16"},
    "d7579926453945ae8b0b214e40ddfccd":{
      "scriptId":"u17"},
    "06dc85d289a74b4d95569c97c490e018":{
      "scriptId":"u18"},
    "1fe32dd66abf4a69bd90d173b82f5567":{
      "scriptId":"u19"},
    "9839d4bc8666406e8c8ea6cc19a4674f":{
      "scriptId":"u20"},
    "f95ff22b10974afab3e64855aaaeb25d":{
      "scriptId":"u21"},
    "7215821aaa1e4a3985fff4effce225ed":{
      "scriptId":"u22"},
    "e9aaea76ac8641e2b5d51558f4cdf5d9":{
      "scriptId":"u23"},
    "1506fe13790046a5b61f137d2aedc263":{
      "scriptId":"u24"},
    "1d7a2f93a2864cec846f111b754a6e64":{
      "scriptId":"u25"},
    "b1d07d7c324d4a1e8c4587b92e67c20b":{
      "scriptId":"u26"},
    "8da286518ec14d2badaadc12a64f1c00":{
      "scriptId":"u27"},
    "c16db1c0996c46fb938fdd1f3dd902d1":{
      "scriptId":"u28"},
    "946d0cf8042749a38d0b123d2161c0a9":{
      "scriptId":"u29"},
    "2bbc05947e854b96be738af16d61195b":{
      "scriptId":"u30"},
    "05c666bda2af4bceb9fd1f7f03d0c3a9":{
      "scriptId":"u31"},
    "4f330ee20785460097c53092af003425":{
      "scriptId":"u32"},
    "36d5275ae6f14272bc0e72d4c66d8bc2":{
      "scriptId":"u33"},
    "563d8689439b4073804cb763d937ea50":{
      "scriptId":"u34"},
    "5dfe94ef1d96454189579724e83a3cb4":{
      "scriptId":"u35"},
    "5574dc41419a4a9fb20bc8d88c38d28f":{
      "scriptId":"u36"},
    "250eb5ad06614dbbbda53ebfcabf3207":{
      "scriptId":"u37"},
    "695d3859d9264296a27af857c4c04dda":{
      "scriptId":"u38"},
    "ba23ddbc6730491a8f6fce83f1ec822c":{
      "scriptId":"u39"},
    "a76f49a60836490ab62c64bf50eb81d7":{
      "scriptId":"u40"},
    "c04f6a3f62bd4064a8cded6aa7dabc5d":{
      "scriptId":"u41"},
    "3a666b89048f400db4a2f655674b3560":{
      "scriptId":"u42"},
    "88b8c6a48e0c40e3aa74f3fa4cc307b9":{
      "scriptId":"u43"}}});