$axure.loadCurrentPage({
  "url":"详情页面.html",
  "generationDate":new Date(1508494786306.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9b84da0c625c422780f3aca6aff0f520",
    "type":"Axure:Page",
    "name":"详情页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c86b5a60c68742a48516ef85a7df75ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":360,
              "height":850}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e86d81a65a854a90b174cea270ea2c88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":70},
                "size":{
                  "width":360,
                  "height":850}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u0.png"}},
{
          "id":"e19f36475dd74d5b9f7894b6c806f755",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":70,
              "y":90},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eded8be5dea1410d8674f9a81f918fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":70,
                  "y":90},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"d5be037a0bea497e9fc6ed8f08154541",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":90},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f62a04cc3be444d87b187e1d2146a38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":90},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u107.png"}},
{
          "id":"e0dc2c1d38b241fa8d2622cde72e430b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e6f8a4ac33b4a7e90b2092b935b6302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":70},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"825cb79165ab45edb52a036e6bb2b749",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":71,
              "y":876},
            "size":{
              "width":179,
              "height":44},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d4b0df422d8476996df42aa3a40ce55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":71,
                  "y":876},
                "size":{
                  "width":179,
                  "height":44},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 转出",
                      "target":{
                        "targetType":"page",
                        "url":"转出.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/详情页面/u8.png"}},
{
          "id":"920b881e6d454c1f9bf8b6fe96431398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":250,
              "y":876},
            "size":{
              "width":179,
              "height":44},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"920213474eb44781906a702b2f7167e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":250,
                  "y":876},
                "size":{
                  "width":179,
                  "height":44},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 转入",
                      "target":{
                        "targetType":"page",
                        "url":"转入.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/详情页面/u10.png"}},
{
          "id":"580e27e39cce466bbf725811cc2fcd7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "lineSpacing":"18px",
            "location":{
              "x":88,
              "y":781},
            "size":{
              "width":324,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"729fb0d8077747a294ed86499f947e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "lineSpacing":"18px",
                "location":{
                  "x":88,
                  "y":781},
                "size":{
                  "width":324,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8df67a69efa84713a85d832150d36c16",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":831},
            "size":{
              "width":324,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入口（开户）/u38_line.png"}},
{
          "id":"421569a4a9d446a2bb1d1eeb644f3c43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"18px",
            "location":{
              "x":396,
              "y":781},
            "size":{
              "width":16,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9be5caba5af4f27981144c49cca5c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"18px",
                "location":{
                  "x":396,
                  "y":781},
                "size":{
                  "width":16,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10267cc351334561bbaffb514244a761",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":800},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e0383445a6414d87ee7384e9f1fcdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":800},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u58.png"}},
{
          "id":"a136594aa7a046cb86b0a281051f3870",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":70,
              "y":134},
            "size":{
              "width":360,
              "height":133},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4c7f34732724dfda7fd49c480b227c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":70,
                  "y":134},
                "size":{
                  "width":360,
                  "height":133},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u19.png"}},
{
          "id":"afc519ff5770499fa183c33f6c65bc05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x7FFFFFFF,
              "opacity":0.498039215803146},
            "lineSpacing":"36px",
            "location":{
              "x":70,
              "y":145},
            "size":{
              "width":360,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c63ed685b8c44ef49f09d0278c80e06a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF,
                  "opacity":0.498039215803146},
                "lineSpacing":"36px",
                "location":{
                  "x":70,
                  "y":145},
                "size":{
                  "width":360,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"843307187040448798c6ca8e46e3d836",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"32px",
            "location":{
              "x":70,
              "y":225},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df0cb6696aeb4cb690aa4b7c3cb82536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"32px",
                "location":{
                  "x":70,
                  "y":225},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7484e9298cb54b89842224272ce03bc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":370,
              "y":90},
            "size":{
              "width":60,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"481057a6b97b48f6971d03cb9e288724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":370,
                  "y":90},
                "size":{
                  "width":60,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账单明细",
                      "target":{
                        "targetType":"page",
                        "url":"账单明细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/详情页面/u25.png"}},
{
          "id":"c92f6e65a4154eda89cebb1433bec120",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":190,
              "y":267},
            "size":{
              "width":120,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d1b199b6db445790ae54cd7470fa35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":190,
                  "y":267},
                "size":{
                  "width":120,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 万份收益",
                      "target":{
                        "targetType":"page",
                        "url":"万份收益.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5dba399776f49b4bb7997cd0beca83a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":310,
              "y":267},
            "size":{
              "width":120,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7707a4a207894159991812ef40a21a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":310,
                  "y":267},
                "size":{
                  "width":120,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 七日年化",
                      "target":{
                        "targetType":"page",
                        "url":"七日年化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"752bbdb9980c45b192ae8a483536e561",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":70,
              "y":267},
            "size":{
              "width":120,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35b3b07889e944cb88b986b83f884c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":70,
                  "y":267},
                "size":{
                  "width":120,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 累计收益",
                      "target":{
                        "targetType":"page",
                        "url":"累计收益.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca847bfb5b9046eda01e62983ac8bab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":71,
              "y":519},
            "size":{
              "width":358,
              "height":8},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b8e92b67d3d4ceba29fee77a60fbd39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":71,
                  "y":519},
                "size":{
                  "width":358,
                  "height":8},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u8.png"}},
{
          "id":"4376bcdc4171409dbae3ab0761062566",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":287},
            "size":{
              "width":10,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情页面/u35_line.png"}},
{
          "id":"fa7057d8029343afb84853416bc9c951",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":287},
            "size":{
              "width":10,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情页面/u35_line.png"}},
{
          "id":"a6614570c940481bae97707fe9c32446",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "lineSpacing":"18px",
            "location":{
              "x":88,
              "y":527},
            "size":{
              "width":324,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9b7d7a5d2f4a62afc4ba387496bae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "lineSpacing":"18px",
                "location":{
                  "x":88,
                  "y":527},
                "size":{
                  "width":324,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f98ed69e49a8431aadb08e3d1077f0ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":545},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6f04fe7653b47b886a8f980beedce7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":545},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u39.png"}},
{
          "id":"64d428cd7ade48dbbff35ac2f8cb7c6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":70},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"299d7d5929484f7284b16c1aae37c6ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":70},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u41.png"}},
{
          "id":"807a286e2fcf49cf8d37330031511f90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":88,
              "y":581},
            "size":{
              "width":324,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed2dbae209845028da8ed09cf296522",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":88,
                  "y":581},
                "size":{
                  "width":324,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9bcda2276394a57a6584d4d0d0e75d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":362,
              "y":598},
            "size":{
              "width":50,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64396b70ff314d8dbbe8ded6376e5e96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":362,
                  "y":598},
                "size":{
                  "width":50,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u45.png"}},
{
          "id":"ffccb410608948b3bc08e644ee34ac37",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":575},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情页面/u47_line.png"}},
{
          "id":"78415f5f1ac04010951e8184ddc17a8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":88,
              "y":645},
            "size":{
              "width":324,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc00c7b38a054cb394415f3483391a7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":88,
                  "y":645},
                "size":{
                  "width":324,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d8d295c419940dfba17a6a8cd41f3fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x7FE81D33},
            "location":{
              "x":362,
              "y":662},
            "size":{
              "width":50,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42390e180c3548019324c5bf631285ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE81D33},
                "location":{
                  "x":362,
                  "y":662},
                "size":{
                  "width":50,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u50.png"}},
{
          "id":"8dce27bfab474150849d2a1089cf6f4a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":639},
            "size":{
              "width":324,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入口（开户）/u38_line.png"}},
{
          "id":"fc17688e70374906a6178ec59d8abaa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":88,
              "y":709},
            "size":{
              "width":324,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9203003a79894ec7a1c9b0adaceea40e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":88,
                  "y":709},
                "size":{
                  "width":324,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5de9f1f995894e9aa43f93114979b65e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":362,
              "y":726},
            "size":{
              "width":50,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"242e7ec2fadb4ad79c3b0a085d3d60b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":362,
                  "y":726},
                "size":{
                  "width":50,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u55.png"}},
{
          "id":"a0289c342a5148a7a67fb6eb8470d601",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":703},
            "size":{
              "width":324,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情页面/u57_line.png"}},
{
          "id":"09345d9a0bee4a53ad62e44ce76b125c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":71,
              "y":773},
            "size":{
              "width":358,
              "height":8},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3865db2917c040458fed44d178e41235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":71,
                  "y":773},
                "size":{
                  "width":358,
                  "height":8},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u8.png"}},
{
          "id":"207bc01730d046b18e00c1ad169ce638",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "lineSpacing":"18px",
            "location":{
              "x":304,
              "y":527},
            "size":{
              "width":108,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afb742fc7a1e4dc88089db21bb76de45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "lineSpacing":"18px",
                "location":{
                  "x":304,
                  "y":527},
                "size":{
                  "width":108,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfcda1b5723148c792b675754660788c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":471},
            "size":{
              "width":10,
              "height":97},
            "rotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/入口（开户）/u154_end.png",
            "line~":"images/详情页面/u62_line.png"}},
{
          "id":"3b4536e6a6ed4b6e966152d1b839d22a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":277.426422119141},
            "size":{
              "width":10,
              "height":110},
            "rotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/详情页面/u63_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情页面/u63_line.png"}},
{
          "id":"e44e703104d7442392759c7907d04942",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":470,
              "y":339},
            "size":{
              "width":230,
              "height":182},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f36d9a66060047249acbf818a9d05e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":470,
                  "y":339},
                "size":{
                  "width":230,
                  "height":182},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u64.png"}},
{
          "id":"76f9dfe4a8a44382a18300543a1d14c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":342},
            "size":{
              "width":358,
              "height":165},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edaf036c9e794518bdda593677c468e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":342},
                "size":{
                  "width":358,
                  "height":165},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页面/u66.png"}},
{
          "id":"1a1b533dc93240bbbeecf666d9076c8b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":326},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情页面/u47_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c86b5a60c68742a48516ef85a7df75ec":{
      "scriptId":"u0"},
    "e86d81a65a854a90b174cea270ea2c88":{
      "scriptId":"u1"},
    "e19f36475dd74d5b9f7894b6c806f755":{
      "scriptId":"u2"},
    "eded8be5dea1410d8674f9a81f918fd0":{
      "scriptId":"u3"},
    "d5be037a0bea497e9fc6ed8f08154541":{
      "scriptId":"u4"},
    "6f62a04cc3be444d87b187e1d2146a38":{
      "scriptId":"u5"},
    "e0dc2c1d38b241fa8d2622cde72e430b":{
      "scriptId":"u6"},
    "3e6f8a4ac33b4a7e90b2092b935b6302":{
      "scriptId":"u7"},
    "825cb79165ab45edb52a036e6bb2b749":{
      "scriptId":"u8"},
    "5d4b0df422d8476996df42aa3a40ce55":{
      "scriptId":"u9"},
    "920b881e6d454c1f9bf8b6fe96431398":{
      "scriptId":"u10"},
    "920213474eb44781906a702b2f7167e4":{
      "scriptId":"u11"},
    "580e27e39cce466bbf725811cc2fcd7b":{
      "scriptId":"u12"},
    "729fb0d8077747a294ed86499f947e38":{
      "scriptId":"u13"},
    "8df67a69efa84713a85d832150d36c16":{
      "scriptId":"u14"},
    "421569a4a9d446a2bb1d1eeb644f3c43":{
      "scriptId":"u15"},
    "f9be5caba5af4f27981144c49cca5c55":{
      "scriptId":"u16"},
    "10267cc351334561bbaffb514244a761":{
      "scriptId":"u17"},
    "d4e0383445a6414d87ee7384e9f1fcdb":{
      "scriptId":"u18"},
    "a136594aa7a046cb86b0a281051f3870":{
      "scriptId":"u19"},
    "e4c7f34732724dfda7fd49c480b227c1":{
      "scriptId":"u20"},
    "afc519ff5770499fa183c33f6c65bc05":{
      "scriptId":"u21"},
    "c63ed685b8c44ef49f09d0278c80e06a":{
      "scriptId":"u22"},
    "843307187040448798c6ca8e46e3d836":{
      "scriptId":"u23"},
    "df0cb6696aeb4cb690aa4b7c3cb82536":{
      "scriptId":"u24"},
    "7484e9298cb54b89842224272ce03bc2":{
      "scriptId":"u25"},
    "481057a6b97b48f6971d03cb9e288724":{
      "scriptId":"u26"},
    "c92f6e65a4154eda89cebb1433bec120":{
      "scriptId":"u27"},
    "e5d1b199b6db445790ae54cd7470fa35":{
      "scriptId":"u28"},
    "d5dba399776f49b4bb7997cd0beca83a":{
      "scriptId":"u29"},
    "7707a4a207894159991812ef40a21a21":{
      "scriptId":"u30"},
    "752bbdb9980c45b192ae8a483536e561":{
      "scriptId":"u31"},
    "35b3b07889e944cb88b986b83f884c9b":{
      "scriptId":"u32"},
    "ca847bfb5b9046eda01e62983ac8bab8":{
      "scriptId":"u33"},
    "8b8e92b67d3d4ceba29fee77a60fbd39":{
      "scriptId":"u34"},
    "4376bcdc4171409dbae3ab0761062566":{
      "scriptId":"u35"},
    "fa7057d8029343afb84853416bc9c951":{
      "scriptId":"u36"},
    "a6614570c940481bae97707fe9c32446":{
      "scriptId":"u37"},
    "5d9b7d7a5d2f4a62afc4ba387496bae8":{
      "scriptId":"u38"},
    "f98ed69e49a8431aadb08e3d1077f0ad":{
      "scriptId":"u39"},
    "e6f04fe7653b47b886a8f980beedce7f":{
      "scriptId":"u40"},
    "64d428cd7ade48dbbff35ac2f8cb7c6a":{
      "scriptId":"u41"},
    "299d7d5929484f7284b16c1aae37c6ce":{
      "scriptId":"u42"},
    "807a286e2fcf49cf8d37330031511f90":{
      "scriptId":"u43"},
    "1ed2dbae209845028da8ed09cf296522":{
      "scriptId":"u44"},
    "e9bcda2276394a57a6584d4d0d0e75d9":{
      "scriptId":"u45"},
    "64396b70ff314d8dbbe8ded6376e5e96":{
      "scriptId":"u46"},
    "ffccb410608948b3bc08e644ee34ac37":{
      "scriptId":"u47"},
    "78415f5f1ac04010951e8184ddc17a8d":{
      "scriptId":"u48"},
    "cc00c7b38a054cb394415f3483391a7e":{
      "scriptId":"u49"},
    "2d8d295c419940dfba17a6a8cd41f3fc":{
      "scriptId":"u50"},
    "42390e180c3548019324c5bf631285ef":{
      "scriptId":"u51"},
    "8dce27bfab474150849d2a1089cf6f4a":{
      "scriptId":"u52"},
    "fc17688e70374906a6178ec59d8abaa5":{
      "scriptId":"u53"},
    "9203003a79894ec7a1c9b0adaceea40e":{
      "scriptId":"u54"},
    "5de9f1f995894e9aa43f93114979b65e":{
      "scriptId":"u55"},
    "242e7ec2fadb4ad79c3b0a085d3d60b2":{
      "scriptId":"u56"},
    "a0289c342a5148a7a67fb6eb8470d601":{
      "scriptId":"u57"},
    "09345d9a0bee4a53ad62e44ce76b125c":{
      "scriptId":"u58"},
    "3865db2917c040458fed44d178e41235":{
      "scriptId":"u59"},
    "207bc01730d046b18e00c1ad169ce638":{
      "scriptId":"u60"},
    "afb742fc7a1e4dc88089db21bb76de45":{
      "scriptId":"u61"},
    "bfcda1b5723148c792b675754660788c":{
      "scriptId":"u62"},
    "3b4536e6a6ed4b6e966152d1b839d22a":{
      "scriptId":"u63"},
    "e44e703104d7442392759c7907d04942":{
      "scriptId":"u64"},
    "f36d9a66060047249acbf818a9d05e57":{
      "scriptId":"u65"},
    "76f9dfe4a8a44382a18300543a1d14c5":{
      "scriptId":"u66"},
    "edaf036c9e794518bdda593677c468e1":{
      "scriptId":"u67"},
    "1a1b533dc93240bbbeecf666d9076c8b":{
      "scriptId":"u68"}}});