$axure.loadCurrentPage({
  "url":"万份收益.html",
  "generationDate":new Date(1509069525842.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"de75d0a1378b47d08a620641b6e6e9e3",
    "type":"Axure:Page",
    "name":"万份收益",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0938be293b3247499bb43d6164bd7d79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df003e7f3fb74643a5fe18d234bd4b15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/万份收益/u0.png"}},
{
          "id":"0c156984499f4694b3dc9a39d20558ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd1d449e1ab4b749caa805fc35bf36e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"d68c57d59c964324b286e6965e1e3a25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3cf3a17374401b88f5474e9724b4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"0648d5b63392471da442f1e98e12ee03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f25cf2de3def4a0891b1dee70f4327a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"5423f1ff4ea74f4088c46e32e06eb149",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81.5,
              "y":130},
            "size":{
              "width":317,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d5d7b36b2bd46288a7d5d30ea0b1803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81.5,
                  "y":130},
                "size":{
                  "width":317,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u10.png"}},
{
          "id":"7a02816fbb6542e18a5383eae814136b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":145},
            "size":{
              "width":126,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/累计收益/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u15_line.png"}},
{
          "id":"a27bf5c47bed452ab8d61239ce096922",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":112},
            "size":{
              "width":220,
              "height":76},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a80103194134f49ae61799754a2238a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":112},
                "size":{
                  "width":220,
                  "height":76},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u16.png"}},
{
          "id":"87ddca1c859d439582641f735693b88f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":299},
            "size":{
              "width":90,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/累计收益/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/累计收益/u12_line.png"}},
{
          "id":"e07e9717631b4bdd92e27f8bb7f79492",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":480,
              "y":263},
            "size":{
              "width":220,
              "height":82},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46603322d00740a9a8387ac67fd22587",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":480,
                  "y":263},
                "size":{
                  "width":220,
                  "height":82},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计收益/u13.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0938be293b3247499bb43d6164bd7d79":{
      "scriptId":"u0"},
    "df003e7f3fb74643a5fe18d234bd4b15":{
      "scriptId":"u1"},
    "0c156984499f4694b3dc9a39d20558ee":{
      "scriptId":"u2"},
    "ccd1d449e1ab4b749caa805fc35bf36e":{
      "scriptId":"u3"},
    "d68c57d59c964324b286e6965e1e3a25":{
      "scriptId":"u4"},
    "1e3cf3a17374401b88f5474e9724b4bb":{
      "scriptId":"u5"},
    "0648d5b63392471da442f1e98e12ee03":{
      "scriptId":"u6"},
    "f25cf2de3def4a0891b1dee70f4327a4":{
      "scriptId":"u7"},
    "5423f1ff4ea74f4088c46e32e06eb149":{
      "scriptId":"u8"},
    "4d5d7b36b2bd46288a7d5d30ea0b1803":{
      "scriptId":"u9"},
    "7a02816fbb6542e18a5383eae814136b":{
      "scriptId":"u10"},
    "a27bf5c47bed452ab8d61239ce096922":{
      "scriptId":"u11"},
    "7a80103194134f49ae61799754a2238a":{
      "scriptId":"u12"},
    "87ddca1c859d439582641f735693b88f":{
      "scriptId":"u13"},
    "e07e9717631b4bdd92e27f8bb7f79492":{
      "scriptId":"u14"},
    "46603322d00740a9a8387ac67fd22587":{
      "scriptId":"u15"}}});