$axure.loadCurrentPage({
  "url":"银行卡列表添卡.html",
  "generationDate":new Date(1509069531232.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d5fe88dacfac4fc387d71ae59a2645f8",
    "type":"Axure:Page",
    "name":"银行卡列表添卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"69c0f3d2285541b48f04bb101c2fe6ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09755d7ab6c1473da015ac40e9d030c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡列表添卡/u0.png"}},
{
          "id":"3839d802990047eea02026e113e20d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5047d51b00e04a9593a8e61b0d60bd3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"da003067887b4dcfb9b628fe2b1a38f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c293f58cad245f4a6f7e9cf4daa75e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"9aa58e7952944f9983b4049354c966d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c9bc09a6d3740088541c9657651b3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"8c9a7f74dae14b44892d134c8f00990d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":340,
              "y":80},
            "size":{
              "width":80,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8dc0dc5d1a94ad5ba0959396a01c10a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":340,
                  "y":80},
                "size":{
                  "width":80,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转入（有xx宝账户）/u10.png"}},
{
          "id":"747f925b5f054fbe8a3c4657a9812f00",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":259},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c767f80035ef450b943594917a07f571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":259},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u20.png"}},
{
          "id":"565c2ab3a82c45f1a5a7b726ab7a0db7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":289},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee2006417db14f469b68407dcdb981f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":289},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"c1fbb31fee534a2a80504af874dba4c3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":289},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5386c9fbf71446308aae96d2e92c4933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":594,
                  "y":289},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"4bf2768959104f7e8d1b2efc11673dbe",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":319},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8732e644c6194994963a757bdfdb1825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":319},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"51f19a11209b4a5fa9cdfb1db4919f17",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":259},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba4d96a2fc9c42c3b9c8f034607bb556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":703,
                  "y":259},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u58.png"}},
{
          "id":"cf58deb1155d4d8493eb8399c25f9c5f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":430},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49e38df0c594442f852feddf66792fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":430},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u58.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "69c0f3d2285541b48f04bb101c2fe6ef":{
      "scriptId":"u0"},
    "09755d7ab6c1473da015ac40e9d030c6":{
      "scriptId":"u1"},
    "3839d802990047eea02026e113e20d56":{
      "scriptId":"u2"},
    "5047d51b00e04a9593a8e61b0d60bd3e":{
      "scriptId":"u3"},
    "da003067887b4dcfb9b628fe2b1a38f0":{
      "scriptId":"u4"},
    "6c293f58cad245f4a6f7e9cf4daa75e7":{
      "scriptId":"u5"},
    "9aa58e7952944f9983b4049354c966d6":{
      "scriptId":"u6"},
    "2c9bc09a6d3740088541c9657651b3b8":{
      "scriptId":"u7"},
    "8c9a7f74dae14b44892d134c8f00990d":{
      "scriptId":"u8"},
    "f8dc0dc5d1a94ad5ba0959396a01c10a":{
      "scriptId":"u9"},
    "747f925b5f054fbe8a3c4657a9812f00":{
      "scriptId":"u10"},
    "c767f80035ef450b943594917a07f571":{
      "scriptId":"u11"},
    "565c2ab3a82c45f1a5a7b726ab7a0db7":{
      "scriptId":"u12"},
    "ee2006417db14f469b68407dcdb981f9":{
      "scriptId":"u13"},
    "c1fbb31fee534a2a80504af874dba4c3":{
      "scriptId":"u14"},
    "5386c9fbf71446308aae96d2e92c4933":{
      "scriptId":"u15"},
    "4bf2768959104f7e8d1b2efc11673dbe":{
      "scriptId":"u16"},
    "8732e644c6194994963a757bdfdb1825":{
      "scriptId":"u17"},
    "51f19a11209b4a5fa9cdfb1db4919f17":{
      "scriptId":"u18"},
    "ba4d96a2fc9c42c3b9c8f034607bb556":{
      "scriptId":"u19"},
    "cf58deb1155d4d8493eb8399c25f9c5f":{
      "scriptId":"u20"},
    "49e38df0c594442f852feddf66792fc1":{
      "scriptId":"u21"}}});