$axure.loadCurrentPage({
  "url":"充值（无xx本地宝账户）.html",
  "generationDate":new Date(1509069531929.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5d022e01493a46f782d0e85ea59d7779",
    "type":"Axure:Page",
    "name":"充值（无XX本地宝账户）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a774e559d4f407385f9e8f43f56328c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235a283edf5b4a10bbc1c51fed020840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u0.png"}},
{
          "id":"1d134f8a03d84239a8e56e8e90d6a72c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1390,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad0548ce5ca3406c91c4c4f240d97bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1390,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u2.png"}},
{
          "id":"a152d80f4dbd48f4a0a143836092b0b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":503,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3df75b7b5ea34c1caa464209095188cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":503,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u4.png"}},
{
          "id":"7f38b330d87748f7ba111922014057ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"066d9d682ab74aca93a1b0a484b0ceda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u6.png"}},
{
          "id":"128a5bfdd9944914af0186d7b5d27ef1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":80,
              "y":413},
            "size":{
              "width":110,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7cae9f0659c40b5a58329a2da30f219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":80,
                  "y":413},
                "size":{
                  "width":110,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u8.png"}},
{
          "id":"a5e94d91963e49e28ad94e726093851a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":280,
              "y":473},
            "size":{
              "width":64,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68fa1414248643b1bfd80acc4f63f48d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":280,
                  "y":473},
                "size":{
                  "width":64,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u10.png"}},
{
          "id":"184663d5a468470b8fef7654355cf108",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":206,
              "y":179},
            "size":{
              "width":68,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19ba8e2a7bcf4b6a8dbec5a12caf79af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":206,
                  "y":179},
                "size":{
                  "width":68,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u12.png"}},
{
          "id":"3c7d3949023347e9a13ce746f42d6ea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":338,
              "y":179},
            "size":{
              "width":82,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f20a4e6a97ea472396dfd29f3b013856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":338,
                  "y":179},
                "size":{
                  "width":82,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u14.png"}},
{
          "id":"5b82170782da44649879c296ab0ff5a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":209,
              "y":348},
            "size":{
              "width":102,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"861322f0d92f407fb484d0f4d3994c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":209,
                  "y":348},
                "size":{
                  "width":102,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u16.png"}},
{
          "id":"613667bbd0fe4b3aabcf82259b90a9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":1060,
              "y":486},
            "size":{
              "width":135,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c6216de015044e89b5228872ee0eb8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":1060,
                  "y":486},
                "size":{
                  "width":135,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u18.png"}},
{
          "id":"12c71352553c47f0bca44bac54b11fcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":1390,
              "y":239},
            "size":{
              "width":91,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"206d516f4fe945f69ae88b577c993476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":1390,
                  "y":239},
                "size":{
                  "width":91,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u20.png"}},
{
          "id":"cf468826a75f4bc9bbb5a3925f518de7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1820,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b2ba2d692d4ff9a6299ced7dfedac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1820,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u22.png"}},
{
          "id":"d3e08df7ac1943f9877b7b2564d8cd62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2262,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14dfff0ac8e347fb9f61fdb2a6476f49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2262,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u24.png"}},
{
          "id":"b51395f83ad74c7d82b852b3a9ad7411",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":1932,
              "y":416},
            "size":{
              "width":135,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51e02e7763fc43f7bbf5cf0c41f13827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":1932,
                  "y":416},
                "size":{
                  "width":135,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u18.png"}},
{
          "id":"84f8bd3554114b8bac6c121bfbbacbc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":2479,
              "y":398},
            "size":{
              "width":108,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c3e02d404e48d2a7585906921e972a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":2479,
                  "y":398},
                "size":{
                  "width":108,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u28.png"}},
{
          "id":"56db01d467b74cdbbca690e349383432",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":2374,
              "y":488},
            "size":{
              "width":135,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d08f8bb2bd4440878ff98f54b2ed7efb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":2374,
                  "y":488},
                "size":{
                  "width":135,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u18.png"}},
{
          "id":"5aa0cf6bf83a4db9b0985b5505eca92c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2723,
              "y":124},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f5f35ac0374041a816ab493124b9e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2723,
                  "y":124},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u32.png"}},
{
          "id":"515ed624da8446bf8c416103732d1dea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":2850,
              "y":181},
            "size":{
              "width":105,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efeda4354bcb424ba18c63aa4bd463f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":2850,
                  "y":181},
                "size":{
                  "width":105,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u34.png"}},
{
          "id":"3ca5632f3d63422ea4359ade0d35a2c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":2939,
              "y":329},
            "size":{
              "width":140,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83bb0102bb7f4a0493c848edc4ae2a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":2939,
                  "y":329},
                "size":{
                  "width":140,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u36.png"}},
{
          "id":"52e91ca2580145b4ab576ef83e5bf346",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "paddingTop":"12",
            "paddingBottom":"12",
            "location":{
              "x":3093,
              "y":298},
            "size":{
              "width":105,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38bc5ba636db487ea2f8072d55278a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "paddingTop":"12",
                "paddingBottom":"12",
                "location":{
                  "x":3093,
                  "y":298},
                "size":{
                  "width":105,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u38.png"}},
{
          "id":"178dcabed17546d18134f348a837d917",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE81D33,
              "opacity":1},
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":564,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b573e75dcbfa4fde8acbecb4432ad5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":564,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u40.png"}},
{
          "id":"ba89cb0232b24fbf990d0275d245f805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":153,
              "y":541},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb65551ee06c429b9de8a8b4c2a635c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":153,
                  "y":541},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值（无xx本地宝账户）/u42.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a774e559d4f407385f9e8f43f56328c":{
      "scriptId":"u0"},
    "235a283edf5b4a10bbc1c51fed020840":{
      "scriptId":"u1"},
    "1d134f8a03d84239a8e56e8e90d6a72c":{
      "scriptId":"u2"},
    "ad0548ce5ca3406c91c4c4f240d97bdf":{
      "scriptId":"u3"},
    "a152d80f4dbd48f4a0a143836092b0b6":{
      "scriptId":"u4"},
    "3df75b7b5ea34c1caa464209095188cd":{
      "scriptId":"u5"},
    "7f38b330d87748f7ba111922014057ab":{
      "scriptId":"u6"},
    "066d9d682ab74aca93a1b0a484b0ceda":{
      "scriptId":"u7"},
    "128a5bfdd9944914af0186d7b5d27ef1":{
      "scriptId":"u8"},
    "e7cae9f0659c40b5a58329a2da30f219":{
      "scriptId":"u9"},
    "a5e94d91963e49e28ad94e726093851a":{
      "scriptId":"u10"},
    "68fa1414248643b1bfd80acc4f63f48d":{
      "scriptId":"u11"},
    "184663d5a468470b8fef7654355cf108":{
      "scriptId":"u12"},
    "19ba8e2a7bcf4b6a8dbec5a12caf79af":{
      "scriptId":"u13"},
    "3c7d3949023347e9a13ce746f42d6ea4":{
      "scriptId":"u14"},
    "f20a4e6a97ea472396dfd29f3b013856":{
      "scriptId":"u15"},
    "5b82170782da44649879c296ab0ff5a1":{
      "scriptId":"u16"},
    "861322f0d92f407fb484d0f4d3994c5f":{
      "scriptId":"u17"},
    "613667bbd0fe4b3aabcf82259b90a9b3":{
      "scriptId":"u18"},
    "9c6216de015044e89b5228872ee0eb8b":{
      "scriptId":"u19"},
    "12c71352553c47f0bca44bac54b11fcc":{
      "scriptId":"u20"},
    "206d516f4fe945f69ae88b577c993476":{
      "scriptId":"u21"},
    "cf468826a75f4bc9bbb5a3925f518de7":{
      "scriptId":"u22"},
    "31b2ba2d692d4ff9a6299ced7dfedac2":{
      "scriptId":"u23"},
    "d3e08df7ac1943f9877b7b2564d8cd62":{
      "scriptId":"u24"},
    "14dfff0ac8e347fb9f61fdb2a6476f49":{
      "scriptId":"u25"},
    "b51395f83ad74c7d82b852b3a9ad7411":{
      "scriptId":"u26"},
    "51e02e7763fc43f7bbf5cf0c41f13827":{
      "scriptId":"u27"},
    "84f8bd3554114b8bac6c121bfbbacbc6":{
      "scriptId":"u28"},
    "27c3e02d404e48d2a7585906921e972a":{
      "scriptId":"u29"},
    "56db01d467b74cdbbca690e349383432":{
      "scriptId":"u30"},
    "d08f8bb2bd4440878ff98f54b2ed7efb":{
      "scriptId":"u31"},
    "5aa0cf6bf83a4db9b0985b5505eca92c":{
      "scriptId":"u32"},
    "b6f5f35ac0374041a816ab493124b9e4":{
      "scriptId":"u33"},
    "515ed624da8446bf8c416103732d1dea":{
      "scriptId":"u34"},
    "efeda4354bcb424ba18c63aa4bd463f1":{
      "scriptId":"u35"},
    "3ca5632f3d63422ea4359ade0d35a2c9":{
      "scriptId":"u36"},
    "83bb0102bb7f4a0493c848edc4ae2a42":{
      "scriptId":"u37"},
    "52e91ca2580145b4ab576ef83e5bf346":{
      "scriptId":"u38"},
    "38bc5ba636db487ea2f8072d55278a3f":{
      "scriptId":"u39"},
    "178dcabed17546d18134f348a837d917":{
      "scriptId":"u40"},
    "b573e75dcbfa4fde8acbecb4432ad5b4":{
      "scriptId":"u41"},
    "ba89cb0232b24fbf990d0275d245f805":{
      "scriptId":"u42"},
    "bb65551ee06c429b9de8a8b4c2a635c1":{
      "scriptId":"u43"}}});