$axure.loadCurrentPage({
  "url":"支持银行及限额.html",
  "generationDate":new Date(1509069531400.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d1ba3989fa1a4f9288fca778924558d1",
    "type":"Axure:Page",
    "name":"支持银行及限额",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff2c70a598104e3a88f47598cf89ef64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":112},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d84db2f95ed54cd49c5b331fbcf8ed15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":112},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支持银行及限额/u0.png"}},
{
          "id":"dae408dd08654e799a06c35799a66f15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":132},
            "size":{
              "width":360,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61957a753f8e4c25aa02c4cf37b32fa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":132},
                "size":{
                  "width":360,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u22.png"}},
{
          "id":"34702d5d0a824799b5912c01d0684e9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":132},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08769738ac92408195f2e0ff98b56268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":132},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"aa4f0d44dd0f4c7b82433e25f0adbe2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":112},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"910d043bc3ca4f4b848d25192a532ad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":112},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"061559ba04b6494db3a3289cf5e0f479",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":60},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d86fd5bcf5f457aa1f119ccadcfd250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":60},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u20.png"}},
{
          "id":"b6f3dc1f2d874aaea8cd1acf1eb87a72",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":189},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdd160c4324e4425a343542e93d89fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":189},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"e68ca4fe1d8f4ac098cadd6aee4c474e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621a223138d8414eb4bff769eb69fa80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":594,
                  "y":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"4136b7e2d1f0405c9430d8ee3e701933",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f78d9a31f54341abc25cb37c37550c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"770432375153464dae9bdbac710383fa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":60},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0865dd8dc7a7468caf9d5bb77f59a2ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":703,
                  "y":60},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u58.png"}},
{
          "id":"cd3ccb3f076a4836a743ae318d5303f7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":237},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ec99771cc74c3db08ee4a29fdbfd62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":237},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u58.png"}},
{
          "id":"f943fd4b2e6e4a249f73faf6be8e3817",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":421},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c022aea7013b4c138c1f81fcaed10f93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":421},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u20.png"}},
{
          "id":"88d3db27c91d4b92b0f9d6b1351b5d3c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":451},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d3d8a6f148149ef8987ef7f913c5994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":451},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"98b4bcdb00954a8587523ae2c6eaba51",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":421},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b81d0ef36dae4aeb9dcdb51c3f06649e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":703,
                  "y":421},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u58.png"}},
{
          "id":"174fc3bbe1954363b3de66679216f29c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":451},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b33713ec343f4735b6d850b455d07352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":594,
                  "y":451},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"4dc2cdaba7fe4f219319560622ec1621",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":591},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27b99c8745a3464f96fd3a1b1454feec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":591},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态一（老用户）/u58.png"}},
{
          "id":"3553124d0e9e4d71a53491b06c79281c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":481},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f37aa15e92404294ee4c2e98a67c83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":481},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "ff2c70a598104e3a88f47598cf89ef64":{
      "scriptId":"u0"},
    "d84db2f95ed54cd49c5b331fbcf8ed15":{
      "scriptId":"u1"},
    "dae408dd08654e799a06c35799a66f15":{
      "scriptId":"u2"},
    "61957a753f8e4c25aa02c4cf37b32fa4":{
      "scriptId":"u3"},
    "34702d5d0a824799b5912c01d0684e9f":{
      "scriptId":"u4"},
    "08769738ac92408195f2e0ff98b56268":{
      "scriptId":"u5"},
    "aa4f0d44dd0f4c7b82433e25f0adbe2c":{
      "scriptId":"u6"},
    "910d043bc3ca4f4b848d25192a532ad0":{
      "scriptId":"u7"},
    "061559ba04b6494db3a3289cf5e0f479":{
      "scriptId":"u8"},
    "8d86fd5bcf5f457aa1f119ccadcfd250":{
      "scriptId":"u9"},
    "b6f3dc1f2d874aaea8cd1acf1eb87a72":{
      "scriptId":"u10"},
    "fdd160c4324e4425a343542e93d89fb8":{
      "scriptId":"u11"},
    "e68ca4fe1d8f4ac098cadd6aee4c474e":{
      "scriptId":"u12"},
    "621a223138d8414eb4bff769eb69fa80":{
      "scriptId":"u13"},
    "4136b7e2d1f0405c9430d8ee3e701933":{
      "scriptId":"u14"},
    "31f78d9a31f54341abc25cb37c37550c":{
      "scriptId":"u15"},
    "770432375153464dae9bdbac710383fa":{
      "scriptId":"u16"},
    "0865dd8dc7a7468caf9d5bb77f59a2ac":{
      "scriptId":"u17"},
    "cd3ccb3f076a4836a743ae318d5303f7":{
      "scriptId":"u18"},
    "56ec99771cc74c3db08ee4a29fdbfd62":{
      "scriptId":"u19"},
    "f943fd4b2e6e4a249f73faf6be8e3817":{
      "scriptId":"u20"},
    "c022aea7013b4c138c1f81fcaed10f93":{
      "scriptId":"u21"},
    "88d3db27c91d4b92b0f9d6b1351b5d3c":{
      "scriptId":"u22"},
    "4d3d8a6f148149ef8987ef7f913c5994":{
      "scriptId":"u23"},
    "98b4bcdb00954a8587523ae2c6eaba51":{
      "scriptId":"u24"},
    "b81d0ef36dae4aeb9dcdb51c3f06649e":{
      "scriptId":"u25"},
    "174fc3bbe1954363b3de66679216f29c":{
      "scriptId":"u26"},
    "b33713ec343f4735b6d850b455d07352":{
      "scriptId":"u27"},
    "4dc2cdaba7fe4f219319560622ec1621":{
      "scriptId":"u28"},
    "27b99c8745a3464f96fd3a1b1454feec":{
      "scriptId":"u29"},
    "3553124d0e9e4d71a53491b06c79281c":{
      "scriptId":"u30"},
    "20f37aa15e92404294ee4c2e98a67c83":{
      "scriptId":"u31"}}});