$axure.loadCurrentPage({
  "url":"升级提示.html",
  "generationDate":new Date(1509069525096.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b2c073ace18409da6bee246fe0c2345",
    "type":"Axure:Page",
    "name":"升级提示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ebfb9b691de64371b1ba3c384e9f3846",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f10977efa3034ecb98431c47229aa9de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u0.png"}},
{
          "id":"74cfa8de48e04b1496bccac899eaf8e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x5BFFFFFF,
              "opacity":0.356862753629684},
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":360,
              "height":130},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2918a15c6b497191efff0c2c2c2589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x5BFFFFFF,
                  "opacity":0.356862753629684},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":360,
                  "height":130},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u2.png"}},
{
          "id":"688cc0b55a7f43fe83ad916a943bbe8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4aafdfc22446b183049f3d8194de1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/状态二（新用户）/u106.png"}},
{
          "id":"15496b7d749e42819d51ba15d6403d4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":360,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d14aa04c99945c0b8c770f0e99ab39c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":360,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入口（开户）/u24.png"}},
{
          "id":"31b9dc72d02644dd8ebef67e7288ddab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":150,
              "y":372},
            "size":{
              "width":230,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e3517b77e8648d7be6cdf9df4ffa5b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":150,
                  "y":372},
                "size":{
                  "width":230,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49dfb704cc704c91a94cce8a418ac6bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":383},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc0dbee387040339524fb6da45f39df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":383},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u10.png"}},
{
          "id":"4f2b96e03ff74aea97c65903d9d1cbd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":150,
              "y":444},
            "size":{
              "width":230,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab9ef890b2f4c2387c1351edf8c9ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":150,
                  "y":444},
                "size":{
                  "width":230,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ab4e23e553c4c828c8425e819120c8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":455},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fafd8fc364b4dee8b3815bbadaa9018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":455},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u10.png"}},
{
          "id":"4a76b297a21b47ad8b213289b9f8a6bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":150,
              "y":515},
            "size":{
              "width":230,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"572a505af001418ab0b2dd097d70acbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":150,
                  "y":515},
                "size":{
                  "width":230,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03dab80a84064efa8bdea93bbf79559f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":526},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312987318d1f48138b45a932041043f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":526},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u10.png"}},
{
          "id":"8af7324d424b477a985a267c9a4e2c65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE81D33},
            "location":{
              "x":78,
              "y":626},
            "size":{
              "width":324,
              "height":44},
            "borderWidth":"-1",
            "linePattern":"none",
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d52b757fa24edfa1a176ebabe1d3b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE81D33},
                "location":{
                  "x":78,
                  "y":626},
                "size":{
                  "width":324,
                  "height":44},
                "borderWidth":"-1",
                "linePattern":"none",
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/升级提示/u20.png"}},
{
          "id":"31d87f4a5f1448fdb95625366ecc226c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"24px",
            "location":{
              "x":78,
              "y":223},
            "size":{
              "width":324,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32b67248d79543149123fa3ef2ab22b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"24px",
                "location":{
                  "x":78,
                  "y":223},
                "size":{
                  "width":324,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"823bece67db94441bb183077866d9c38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":78,
              "y":270},
            "size":{
              "width":324,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"574f3e3f797a42b9a3906929e878077b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":78,
                  "y":270},
                "size":{
                  "width":324,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68513e413187411a80e258adac4c7795",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "verticalAlignment":"middle",
            "location":{
              "x":78,
              "y":321},
            "size":{
              "width":324,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5a25d8fdd874696843c80ad5e9b695d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "verticalAlignment":"middle",
                "location":{
                  "x":78,
                  "y":321},
                "size":{
                  "width":324,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18a805cae83a4942a525aab7d50d34a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"20px",
            "location":{
              "x":78,
              "y":600},
            "size":{
              "width":324,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"566bf46e5eff4852893c1d5bf6f32b2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":78,
                  "y":600},
                "size":{
                  "width":324,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ebfb9b691de64371b1ba3c384e9f3846":{
      "scriptId":"u0"},
    "f10977efa3034ecb98431c47229aa9de":{
      "scriptId":"u1"},
    "74cfa8de48e04b1496bccac899eaf8e7":{
      "scriptId":"u2"},
    "0a2918a15c6b497191efff0c2c2c2589":{
      "scriptId":"u3"},
    "688cc0b55a7f43fe83ad916a943bbe8e":{
      "scriptId":"u4"},
    "0d4aafdfc22446b183049f3d8194de1e":{
      "scriptId":"u5"},
    "15496b7d749e42819d51ba15d6403d4a":{
      "scriptId":"u6"},
    "0d14aa04c99945c0b8c770f0e99ab39c":{
      "scriptId":"u7"},
    "31b9dc72d02644dd8ebef67e7288ddab":{
      "scriptId":"u8"},
    "0e3517b77e8648d7be6cdf9df4ffa5b2":{
      "scriptId":"u9"},
    "49dfb704cc704c91a94cce8a418ac6bf":{
      "scriptId":"u10"},
    "adc0dbee387040339524fb6da45f39df":{
      "scriptId":"u11"},
    "4f2b96e03ff74aea97c65903d9d1cbd4":{
      "scriptId":"u12"},
    "eab9ef890b2f4c2387c1351edf8c9ace":{
      "scriptId":"u13"},
    "6ab4e23e553c4c828c8425e819120c8d":{
      "scriptId":"u14"},
    "1fafd8fc364b4dee8b3815bbadaa9018":{
      "scriptId":"u15"},
    "4a76b297a21b47ad8b213289b9f8a6bd":{
      "scriptId":"u16"},
    "572a505af001418ab0b2dd097d70acbf":{
      "scriptId":"u17"},
    "03dab80a84064efa8bdea93bbf79559f":{
      "scriptId":"u18"},
    "312987318d1f48138b45a932041043f4":{
      "scriptId":"u19"},
    "8af7324d424b477a985a267c9a4e2c65":{
      "scriptId":"u20"},
    "c3d52b757fa24edfa1a176ebabe1d3b9":{
      "scriptId":"u21"},
    "31d87f4a5f1448fdb95625366ecc226c":{
      "scriptId":"u22"},
    "32b67248d79543149123fa3ef2ab22b5":{
      "scriptId":"u23"},
    "823bece67db94441bb183077866d9c38":{
      "scriptId":"u24"},
    "574f3e3f797a42b9a3906929e878077b":{
      "scriptId":"u25"},
    "68513e413187411a80e258adac4c7795":{
      "scriptId":"u26"},
    "c5a25d8fdd874696843c80ad5e9b695d":{
      "scriptId":"u27"},
    "18a805cae83a4942a525aab7d50d34a5":{
      "scriptId":"u28"},
    "566bf46e5eff4852893c1d5bf6f32b2a":{
      "scriptId":"u29"}}});